Vagrant.configure("2") do |config|

    # db01 VM        
    config.vm.define "db01" do |db01|
      db01.vm.box = "centos/7"
      db01.vm.hostname = "db01"
      db01.vm.network "private_network", ip: "192.168.56.43"
  
      db01.vm.provision "shell", inline: <<-SHELL
        yum install -y wget unzip mariadb-server
        systemctl start mariadb
        systemctl enable mariadb
        # done
      SHELL
    end
  
    # web01 VM
    config.vm.define "web01" do |web01|
      web01.vm.box = "ubuntu/focal64"
      web01.vm.hostname = "web01"
      web01.vm.network "private_network", ip: "192.168.56.41"
      
      web01.vm.provision "shell", inline: <<-SHELL
        sudo apt update
        sudo apt install -y apache2
        sudo systemctl start apache2
        sudo systemctl enable apache2
        # Other provisioning commands for web01...
      SHELL
    end
    
    # web02 VM
    config.vm.define "web02" do |web02|
      web02.vm.box = "ubuntu/focal64"
      web02.vm.hostname = "web02"
      web02.vm.network "private_network", ip: "192.168.56.42"
      
      web02.vm.provision "shell", inline: <<-SHELL
        sudo apt update
        sudo apt install -y apache2
        sudo systemctl start apache2
        sudo systemctl enable apache2
        # Other provisioning commands for web02...
      SHELL
    end  
end
  